openapi: 3.0.3
info:
  title: Bee Travels Flights V2 Service
  version: 1.0.0
  description: Flight service for bee travels application
  license:
    name: Apache 2.0
    url: https://github.com/bee-travels/bee-travels-node/blob/master/LICENSE
