language: node_js

node_js:
  - 12

services:
  - docker

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --immutable --immutable-cache --check-cache

jobs:
  include:
    - stage: dep-check
      name: Dependencies Check
      script: yarn constraints

    - stage: lint
      name: Lint
      script: yarn lint

    - stage: test
      name: Test
      script: yarn test

    - stage: deploy
      name: Docker image build
      script: skip
      deploy:
      - provider: script
        skip_cleanup: true
        script: .travis/build-and-push.sh
        on:
          branch: master
