---
version: '3.3'

services:
  ui:
    build: src/ui
    ports:
      - "9000:9000"
    depends_on:
      - destination
      - hotel
      - currencyexchange
    environment:
      - DESTINATION_URL=http://destination:9001
      - HOTEL_URL=http://hotel:9101
      - CURRENCY_EXCHANGE_URL=http://currencyexchange:9201

  destination:
    build: src/destination
    ports:
      - "9001:9001"

  hotel:
      build: src/hotel
      ports:
        - "9101:9101"

  currencyexchange:
    build: src/currencyexchange
    ports:
      - "9201:9201"
