---
version: '3.3'
services:
db2:
    image: ibmcom/db2
    restart: always
    ports:
      - "50000:50000"
    privileged: true
    environment:
      - DB2INST1_PASSWORD=admin
      - LICENSE=accept
      - DBNAME=checkout
    volumes:
      - /var/lib/database


#docker run -itd --name mydb2 --privileged=true -p 50000:50000 -e LICENSE=accept -e DB2INST1_PASSWORD=admin -e DBNAME=testdb -v <db storage dir>:/database ibmcom/db2
