swagger: '2.0'
info:
  description: >-
    This is a microservice that handles destination location data for Bee Travels
  version: 1.0.0
  title: Bee Travels Destinations Data Service
  contact:
    email: maxshapiro32@ibm.com
  license:
    name: Apache 2.0
    url: 'https://github.com/bee-travels/bee-travels-node/blob/master/LICENSE'
host: 'localhost:4000'
basePath: /api/v1
tags:
  - name: Destinations
    description: Operations associated with destination data
schemes:
  - http
paths:
  /destinations:
    get:
      tags:
        - Destinations
      summary: Gets list of destination locations from the data source
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: Successfully got list of destination locations
        '500':
          description: Internal Server Error
  /destinations/{city}/{country}:
    get:
      tags:
        - Destinations
      summary: Gets data associated with given destination location
      description: ''
      produces:
        - application/json
      parameters:
        - in: path
          name: city
          description: City name for destination location
          required: true
        - in: path
          name: country
          description: Country name for destination location
          required: true
      responses:
        '200':
          description: Successfully got destination location data
        '500':
          description: Internal Server Error
